### ISSUE TITLE
RRA / RRD files not created in Cacti 1.0

### ISSUE THREAD

**Issue by jangrewe** [glenpp/cacti-uloganalyser#4]
My Cacti was complaining that there were no RRAs for new graphs, and i wouldn't create them either. While investigating this issue i noticed that there were also no Data Source Templates for those Data Sources, even though they were being referenced.

My solution was to go to each Data Source that it complained about, click "Edit Data Template" and then save that template, et voilá, they showed up in the Data Source Templates list and everything started to work.

**Comment by glenpp** [comment]
Hmmm... sounds like the link between graph and data templates might have been broken somehow. Is there particular templates this affects? I've done a quick once-over on the postfix stuff and there seems to be data sources in the .xml, but I can't be sure which templates or if there's a problem importing these in a particular Cacti version.

Could you let me know more detail?

**Comment by jangrewe** [comment]
This was mainly for the spamd and clamav templates, but i also added new graphs for dovecot and postfix where this happened, so i'd say "all of them" ;-)

Sorry that i didn't mention this before, but this is the shiny new Cacti 1.0 (upgraded from 0.8.8<somethingrecent>).

**Comment by glenpp** [comment]
I've build myself a test box with Cacti 1.0.1 and I'm not seeing problems with rrd files being created after importing clamav and spamd templates. I notice a bunch of fixes relating to graphs and data sources between 1.0.0 and 1.0.1 - is it possible that this is a compatibility issue with Cacti that's been fixed in 1.0.1 or something relating to upgrading 0.8.8->1.0.x?
